config/routes.rb
Rails.application.routes.draw do
  
  
	get 'pages/static_lp'
	get 'pages/secret_page'
	get 'pages/admin_interface'

	post 'pages/admin_interface', to: 'pages#admin_interface'

	get 'pages/home_page'
	root 'pages#landing_page'

	devise_for :admins, controllers: { registrations: 'admins/registrations' }
	
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :messages, only: [:new, :create]
	resources :charges
	
	devise_for :users, controllers: {
	omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations', sessions: 'users/sessions' 
	}
	
	scope '/admin' do
		resources :users
	end
	
	match "/404", to: "erreurs#page_introuvable", via: :all
  	match "/422", to: "erreurs#erreur_interne", via: :all
  	match "/500", to: "erreurs#erreur_interne", via: :all
  
end

app/views/pages/admin_interface.html.erb
<div class="div-admin-header">
	<div>
	<h1>ADMINISTRATEUR </h1>

 <h2>Gestion des Utilisateurs</h2>
 
</div>

</div>

<hr>
<div class="div-admin-main-stats">
	<div class="div-admin-stats">
		<div class="div-admin-name">
			Bonjour Administrateur <%= current_admin.first_name %> <%= current_admin.last_name %>.
		</div>

		<div class="div-admin-stats-data">
			Vous avez <%= @users_number %> Utilisateurs inscrits sur votre site.
		</div>

		<div class="div-admin-stats-data">
			Vous avez <%= @users_no_paid %> Utilisateurs qui n'ont pas réglé la cotisation
		</div>
	</div>
	<div class="div-admin-stats-bis">
		<div class="div-admin-stats-1">
			<%= link_to "Sign out", destroy_admin_session_path, method: :delete, class:"btn btn-warning btn-lg js-scroll-trigger" %>
		</div>
		<div class="div-admin-stats-1">
			<div>
	
	<%= link_to "Creer un Utilisateur", new_user_path, class: "btn btn-danger btn-lg js-scroll-trigger"%>
	
</div>
		</div>
	</div>
</div>
<div class="div-searsh-bar">
	<%= form_tag(pages_admin_interface_path, method: 'post') do%>
	<h4>Recherche d'Utilisateurs:</h4>
	<div class="input-group mb-3">
		<input type="text" id="name" name="name" size="1" placeholder="prénom nom" class="form-control" aria-describedby="button-addon2" />
  <div class="input-group-append">
    <button class="btn btn-outline-secondary" type="submit" id="button-addon2" name="commit">Go</button>
  </div>
</div>
	<% end %>
</div>

<div class="div-main">
<div class="div-admin-table">
	<div class="div-admin-table-bis-4"> Action</div>
	<div class="div-admin-table-1-bis"> ID</div>
	<div class="div-admin-table-1-long"> Prénom</div>
	<div class="div-admin-table-1-long"> Nom</div>
	<div class="div-admin-table-1-long"> Email</div>
	<div class="div-admin-table-1"> Phone</div>
	<div class="div-admin-table-bis-3"> Poids</div>
	<div class="div-admin-table-bis-3"> Ceinture</div>

	
</div>

<% @users.each do |v| %>
	<% if v.first_name.downcase.match?(@first_name) or v.last_name.downcase.match?(@last_name) %>
		<div class="div-admin-table-2">
					<div class="div-admin-table-bis-4"> 
						<%= link_to "Modifier", edit_user_path(v.id), class: "btn btn-primary btn-sm js-scroll-trigger"%></div>

					<div class="div-admin-table-1-bis"> <%= v.id %> </div>
					<div class="div-admin-table-1-long"> <%= if v.first_name != nil; v.first_name end%></div>
					<div class="div-admin-table-1-long"> <%= if v.last_name != nil; v.last_name end %></div>
					<div class="div-admin-table-1-long"> <%= v.email %></div>
					<div class="div-admin-table-1"> <%= v.phone %></div>
					<div class="div-admin-table-bis-3"> <%= v.weight %></div>
					<div class="div-admin-table-bis-3"> <%= if v.belt != nil; v.belt end %></div>
					

		</div>
	<% elsif (@first_name == " ") && (@last_name == " ") %>
		<div class="div-admin-table-2">
					<div class="div-admin-table-bis-4"> 
						<%= link_to "Modifier", edit_user_path(v.id), class: "btn btn-primary btn-sm js-scroll-trigger"%></div>

					<div class="div-admin-table-1-bis"> <%= v.id %> </div>
					<div class="div-admin-table-1-long"> <%= if v.first_name != nil; v.first_name end%></div>
					<div class="div-admin-table-1-long"> <%= if v.last_name != nil; v.last_name end %></div>
					<div class="div-admin-table-1-long"> <%= v.email %></div>
					<div class="div-admin-table-1"> <%= v.phone %></div>
					<div class="div-admin-table-bis-3"> <%= v.weight %></div>
					<div class="div-admin-table-bis-3"> <%= if v.belt != nil; v.belt end %></div>
					

		</div>	
	<% else %>	
	<% end %>
<% end %>
</div>

app/views/pages/secret_page.html.erb
<% if current_user.first_name == nil || current_user.last_name == nil || current_user.age == nil || current_user.profession == nil || current_user.weight == nil || current_user.phone == nil%>
<%= link_to "PROFIL IMCOMPLET", edit_user_registration_path, class: "btn btn-secondary btn-block" %>
<% end %>

<div class="div-container-global">
  
    <div class="div-container-title">
        <h1>Bienvenue <%= first_name_nil(current_user.first_name) %> <%= last_name_nil(current_user.last_name) %></h1>
    </div>
    <div class="div-container-body">

      <div class="div-container-belt", style="background-color: <%=color_belt(current_user.belt)%>;">
     
      </div>

    <div class="div-container-body-infos">
      <div class="div-container-img">
        <%= image_tag "avatar.jpg", :class => "d-block w-100"%>
      </div>
      <div class="div-container-body-infos-sub">
        <div class="div-infos-title">
          <div>Email:</div>
          <div>Téléphone:</div>
          <div>Ceinture:</div> 
          <div>Age:</div>
          <div>Poids:</div>
          <div>Profession:</div>
          <div>Nationalité:</div>

                     
        </div>

        <div class="div-infos-values">
          <div> <%= name_nil(current_user.email) %></div>
          <div> <%= name_nil(current_user.phone) %></div>
          <div> <%= name_nil(current_user.belt) %> </div>
          <div> <%= name_nil_1(current_user.age) %></div>
          <div> <%= name_nil_2(current_user.weight) %> </div>
          <div> <%= name_nil(current_user.profession) %></div>
          <div> <%= name_nil(current_user.nationality) %></div>
        </div>
      </div>

      <div class="div-container-body-subscription">
          <div class="div-container-body-subscription-title">
            ABONNEMENT
          </div>
          <div class="div-container-body-subscription-content">
            <div class="div-container-body-subscription-content-1">
              <%= contract_real_name(current_user_contract_name) %>
            </div>

          <div>
            <%= puts_contract_start %>
          </div>
          <div>
            <%= puts_contract_end %>
          </div>
          <div class="text-center">
            <% if contract_real_time(current_user_contract_name) != nil %> 
            <%= contract_real_time(current_user_contract_name) %> mois
            <% else %>
            <strong>Aucun</strong>
            <% end %>
          </div>
          </div>
          
        </div>
    
    </div>

  <div class="div-container-foot">
    <div class="div-container-foot-sub">
      <%= link_to "Me Déconnecter", destroy_user_session_path, method: :delete, class: "btn btn-danger", style: "width: 300px;" %>
    </div>
    <div class="div-container-foot-sub">
      <%= link_to "Modifier mon Profil", edit_user_registration_path, class: "btn btn-default" %>
    </div>
    <div class="div-container-foot-sub">
       <%= link_to "Annuler", :back, class: "btn btn-default" %>
    </div>
  </div>

</div> 