config/routes.rb
Rails.application.routes.draw do
  
  
	get 'pages/static_lp'
	get 'pages/secret_page'
	get 'pages/admin_interface'

	post 'pages/admin_interface', to: 'pages#admin_interface'

	get 'pages/home_page'
	root 'pages#landing_page'

	devise_for :admins, controllers: { registrations: 'admins/registrations' }
	
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :messages, only: [:new, :create]
	resources :charges
	
	devise_for :users, controllers: {
	omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations', sessions: 'users/sessions' 
	}
	
	scope '/admin' do
		resources :users
	end
	
	match "/404", to: "erreurs#page_introuvable", via: :all
  	match "/422", to: "erreurs#erreur_interne", via: :all
  	match "/500", to: "erreurs#erreur_interne", via: :all
  
end

app/views/layouts/_banniere.html.erb
  <header>
          <%= image_tag "ban2.jpg", :class => "img-fluid", :style => "filter:grayscale(20%);"%>
  </header>

app/views/layouts/_caroussel.html.erb
<div class="carousel-inner">
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">

        <div class="carousel-item active">
           <%= image_tag "GB-Banner2.jpg", :class => "d-block w-100", :style => "filter:grayscale(30%);"%>
          <div class="carousel-caption d-none d-md-block">
          <h1><mark>Jiu-Jitsu</mark></h1>
          <h1><mark>For</mark></h1>
          <h1><mark>Everyone</mark></h1>
          <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="#contact">Rejoignez-nous</a>
          </div>
        </div>
        <div class="carousel-item">
           <%= image_tag "GB-banner-bg.jpg", :class => "d-block w-100", :style => "filter:grayscale(30%);"%>
          <div class="carousel-caption d-none d-md-block">
            <h1><mark>Jiu-Jitsu</mark></h1>
            <h1><mark>For</mark></h1>
            <h1><mark>Everyone</mark></h1>
            <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="#contact">Rejoignez-nous</a>
          </div>
        </div>
        <div class="carousel-item">
          <%= image_tag "GB-Banner3.jpg", :class => "d-block w-100", :style => "filter:grayscale(30%);"%>
          <div class="carousel-caption d-none d-md-block">
            <h1><mark>Jiu-Jitsu</mark></h1>
            <h1><mark>For</mark></h1>
            <h1><mark>Everyone</mark></h1>
            <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="#contact">Rejoignez-nous</a>
          </div>
        </div>
      </div>

      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show" role="alert">
    <%= msg %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
  <nav class="navbar navbar-expand-lg fixed-top navbar-shrink" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="#page-top">
        <%= image_tag "LogoGB-2.png", :class => "img-fluid", :style => "width:12%; height:12%;"%>
         GRACIE BARRA PARIS
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav text-uppercase ml-auto">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#services">Valeurs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#portfolio">Cours</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
          </li>
          <li class="nav-item">
            <%= link_to 'Tarifs', pages_static_lp_path, class: "nav-link" %>
          </li>
          <li>
          <div class="dropdown nav-item" > 
            <a class="nav-link dropdown-toggle"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >Mon Compte
            </a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" id="dropdownID">
                <%= link_to 'Accueil', pages_home_page_path, class: "nav-link" %>
                <%= link_to 'Se Connecter', new_user_session_path, class: "nav-link" %>
                <%= link_to "S'enregistrer", new_user_registration_path, class: "nav-link" %>
              </div>
            </div>
          </li>
        </ul>
      </div>



    </div>

  </nav>
  <%= render "layouts/flash" %>

app/views/layouts/_navbar2.html.erb
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg fixed-top navbar-shrink" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href=<%= root_path %>>
        <%= image_tag "LogoGB-2.png", :class => "img-fluid", :style => "width:15%; height:15%;"%>
         GRACIE BARRA PARIS
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" >
        <ul class="navbar-nav text-uppercase ml-auto">
          
          <li class="nav-item">
            <a class="nav-link" href="#code">Code</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#planning">Planning</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#histoire">Histoire</a>
          </li>
          <li class="nav-item">
            <%= link_to 'Tarifs', pages_static_lp_path, class: "nav-link" %>
          </li>
          <li>
          <!-- Drop down -->
              <div class="dropdown nav-item" > 
            <a class="nav-link dropdown-toggle"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >Mon Compte
            </a>

            <% if user_signed_in? %>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" id="dropdownID">
                <%= link_to 'Profil', pages_secret_page_path(current_user.id), class: "nav-link" %>
                <%= link_to 'Accueil', pages_home_page_path, class: "nav-link" %>
                <%= link_to "Déconnexion", destroy_user_session_path, class: "nav-link", :method => "delete" %> 
              </div>
            <% elsif admin_signed_in? %>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" id="dropdownID">
                <%= link_to 'DashBoard', pages_admin_interface_path(current_admin.id), class: "nav-link" %>
                <%= link_to 'Accueil', pages_home_page_path, class: "nav-link" %>
                <%= link_to "Déconnexion", destroy_admin_session_path, class: "nav-link", :method => "delete" %> 
              </div>
              <% else %>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" id="dropdownID">
                <%= link_to 'Accueil', pages_home_page_path, class: "nav-link" %>
                <%= link_to 'Se Connecter', new_user_session_path, class: "nav-link" %>
                <%= link_to "S'enregistrer", new_user_registration_path, class: "nav-link" %>
              </div>
            <% end %>
            
              
            </div>
            
          
          </li>
        </ul>
      </div>
    </div>

  </nav>
  <%= render "layouts/flash" %>

app/views/layouts/_navbar3.html.erb
<!-- Navigation -->
  <nav class="navbar navbar-expand-lg fixed-topnavbar-shrink" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href=<%= root_path %>>
        <%= image_tag "LogoGB-2.png", :class => "img-fluid", :style => "width:15%; height:15%;"%>
         GRACIE BARRA PARIS
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" >
        <ul class="navbar-nav text-uppercase ml-auto">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#services">Valeurs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#portfolio">Cours</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
          </li>
          <li class="nav-item">
            <%= link_to 'Tarifs', pages_static_lp_path, class: "nav-link" %>
          </li>
          <li>
            <div class="dropdown nav-item"> 
              <a class="nav-link dropdown-toggle"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Mon Compte
              </a>
              <% if admin_signed_in? %>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" id="dropdownID">
                <%= link_to 'DashBoard', pages_admin_interface_path(current_admin.id), class: "nav-link" %>
                <%= link_to 'Accueil', pages_home_page_path, class: "nav-link" %>
                <%= link_to "Déconnexion", destroy_admin_session_path, class: "nav-link", :method => "delete" %> 
              </div> 
              <% else %>          
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" id="dropdownID">
                <%= link_to 'Profil', pages_secret_page_path(current_user.id), class: "nav-link" %>
                <%= link_to 'Accueil', pages_home_page_path, class: "nav-link" %>
                <%= link_to "Déconnexion", destroy_user_session_path, class: "nav-link", :method => "delete" %> 
              </div>
              <% end %>
            </div>
          </li>
        </ul>
      </div>
    </div>

  </nav>
  <%= render "layouts/flash" %>

app/views/layouts/_navbar4.html.erb
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-shrink" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href=<%= root_path %>>
        <%= image_tag "LogoGB-2.png", :class => "img-fluid", :style => "width:10%; height:10%;"%>
         GRACIE BARRA PARIS
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" >
        <ul class="navbar-nav text-uppercase ml-auto">
          <li class="nav-item">
            <%= link_to 'Tarifs', pages_static_lp_path, class: "nav-link" %>
          </li>
          <!-- Drop down -->
            <div class="dropdown nav-item"> 
              <a class="nav-link dropdown-toggle"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Mon Compte
              </a>
              <% if admin_signed_in? %>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" id="dropdownID">
                <%= link_to 'DashBoard', pages_admin_interface_path(current_admin.id), class: "nav-link" %>
                <%= link_to 'Accueil', pages_home_page_path, class: "nav-link" %>
                <%= link_to "Déconnexion", destroy_admin_session_path, class: "nav-link", :method => "delete" %> 
              </div> 
              <% else %>  
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" id="dropdownID">
                  <%= link_to 'Profil', pages_secret_page_path(current_user.id), class: "nav-link" %>
                  <%= link_to 'Accueil', pages_home_page_path, class: "nav-link" %>
                  <%= link_to "Déconnexion", destroy_user_session_path, class: "nav-link", :method => "delete" %>             
               </div> 
               <% end %>
             </div>             
          </li>
        </ul>
      </div>
    </div>

  </nav>
  <%= render "layouts/flash" %>

app/views/layouts/_navbar5.html.erb
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-shrink" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href=<%= root_path %>>
        <%= image_tag "LogoGB-2.png", :class => "img-fluid", :style => "width:7%; height:7%;"%>
         GRACIE BARRA PARIS
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" >
        <ul class="navbar-nav text-uppercase ml-auto">
          <li>
        <div class="dropdown nav-item" > 
            <a class="nav-link dropdown-toggle"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >Mon Compte
            </a>
            <!-- Drop down -->
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" id="dropdownID">
                <%= link_to 'Accueil', pages_home_page_path, class: "nav-link" %>
                <%= link_to 'Se Connecter', new_user_session_path, class: "nav-link" %>
                <%= link_to "S'enregistrer", new_user_registration_path, class: "nav-link" %>
              </div>   
            </div>
          </li>
          </ul>
      </div>
    </div>

  </nav>
  <%= render "layouts/flash" %>

app/views/layouts/_navbarbis.html.erb
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-shrink" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href=<%= root_path %>>
        <%= image_tag "LogoGB-2.png", :class => "img-fluid", :style => "width:10%; height:10%;"%>
         GRACIE BARRA PARIS
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" >
        <ul class="navbar-nav text-uppercase ml-auto">
          <!-- Drop down -->
            <div class="dropdown nav-item"> 
              <a class="nav-link dropdown-toggle"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Mon Compte
              </a>
              <% if admin_signed_in? %>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" id="dropdownID">
                <%= link_to 'DashBoard', pages_admin_interface_path(current_admin.id), class: "nav-link" %>
                <%= link_to 'Accueil', pages_home_page_path, class: "nav-link" %>
                <%= link_to "Déconnexion", destroy_admin_session_path, class: "nav-link", :method => "delete" %> 
              </div> 
              <% else %>  
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" id="dropdownID">
                  <%= link_to 'Profil', pages_secret_page_path(current_user.id), class: "nav-link" %>
                  <%= link_to 'Accueil', pages_home_page_path, class: "nav-link" %>
                  <%= link_to "Déconnexion", destroy_user_session_path, class: "nav-link", :method => "delete" %>             
               </div> 
               <% end %>
             </div>             
          </li>
        </ul>
      </div>
    </div>

  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
 
    <script src="https://kit.fontawesome.com/b73e119146.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>

    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>

    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <link href="https://fonts.googleapis.com/css?family=Archivo:500i|Josefin+Sans:600i|Overpass:600i|Prompt:500i&display=swap" rel="stylesheet">
    
    <title>GracieHaApp</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

      


      <script src="https://kit.fontawesome.com/b73e119146.js"></script>

  </head>
  <header>
    <% if user_signed_in? || admin_signed_in? && current_page?(root_path) %>
    <%= render "layouts/navbar3" %>
  <% elsif user_signed_in? || admin_signed_in? && current_page?(pages_home_page_path) %>
    <%= render "layouts/navbar2" %>
    
  <% elsif user_signed_in? || admin_signed_in? %>
    <%= render "layouts/navbar4" %>
    <%= render "layouts/banniere" %>
  <% elsif user_signed_in? || admin_signed_in? && current_page?(new_charge_path) %>
  <%= render "layouts/navbarbis" %>
    <%= render "layouts/banniere" %>
  <% elsif current_page?(root_path) %>
    <%= render "layouts/navbar" %>
  <% elsif current_page?(pages_home_page_path) %>
    <%= render "layouts/navbar2" %>
  <% else %>
    <%= render "layouts/navbar5" %>
    <%= render "layouts/banniere" %>
  <% end %>
  </header>

  <body id="page-top">

    <%= yield %>
  
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>

  <footer class="footer">
    <%= render "layouts/footer" %>
  </footer>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://kit.fontawesome.com/b73e119146.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>

    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>

    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <link href="https://fonts.googleapis.com/css?family=Archivo:500i|Josefin+Sans:600i|Overpass:600i|Prompt:500i&display=swap" rel="stylesheet">

  	<meta charset="utf-8">
  	<%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/b73e119146.js"></script>

  	<title>Paiement Stripe</title>
	
  </head>
  <header>
    <%= render "layouts/navbarbis" %>
    <%= render "layouts/banniere" %>
  </header>
  <body>
    <%= yield %>
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
  <footer class="footer">
    <%= render "layouts/footer" %>
  </footer>
</html>